# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  
- task: GoTool@0
  inputs:
    version: '1.19.4'
  displayName: 'Install Go Library'

- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'
  displayName: 'Install Terraform'
- task: CmdLine@2
  inputs:
    script: |
      echo "setting environment Variables"
      bash -c export ARM_CLIENT_ID=  "$(ARM_CLIENT_ID)"
      bash -c export ARM_CLIENT_SECRET="$(ARM_CLIENT_SECRET)"
      bash -c export ARM_SUBSCRIPTION_ID="$(ARM_SUBSCRIPTION_ID)"
      bash -c export ARM_TENANT_ID="$(ARM_TENANT_ID)"
      echo "Environment Variables exported"
  displayName: 'Set Environment Variables'

- task: CmdLine@2
  inputs:
    script: |
      cd test
      go mod init test 
      go mod tidy 
      az login -u "$(username)" -p "$(password)" 
  displayName: 'Az LogIn'

- task: CmdLine@2
  inputs:
    script: |
      cd test
      go mod init test 
      go mod tidy 
      az login -u "$(username)" -p "$(password)" 
      go test -v
      echo "tested successfully"
  displayName: 'go test'



- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
